#auto: true
safe: false
#include: ./pages/
plugins: ./_plugins/
baseurl: /docs/3.5/
#source:      ./pages/
#destination:
#layouts:     ./_layouts/
#permalink: /:title.html

#CFEngine addon
# CFE_OUTPUT turn on special rules for output
CFE_OUTPUT: true

#CFE_DIR - output folder if CFE_OUTPUT turned on
CFE_DIR: _site
#to create correct links in sitemap
CFE_manuals_version: 3.5

paginate: 500

pygments: true
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
#markdown:  rdiscount
#pandoc:  true
asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: docs/3.5/assets       # Default = nil
  gzip: false             # Default = false
