#auto: true
safe: false
#include: ./pages/
plugins: ./_plugins/
#url: https://cfengine.com/tmp_doc/
base: nil
#source:      ./pages/
#destination: 
#layouts:     ./_layouts/
#permalink: /:title.html

#CFEngine addon
# CFE_OUTPUT turn on special rules for output
CFE_OUTPUT: true

#CFE_DIR - output folder if CFE_OUTPUT turned on
CFE_DIR: _site

paginate: 500

pygments: true
#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
markdown:  redcarpet2
pandoc:  true
asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  #display_path: tmp_docs/assets       # Default = nil
  display_path: assets       # Default = nil
  gzip: false             # Default = false
